// packages/react-query/src/index.tsx
import React, { createContext, useContext, useMemo } from 'react';
import {
    useQuery as __useQuery,
    useMutation as __useMutation,
    UseQueryOptions,
    UseMutationOptions,
    UseQueryResult,
    UseMutationResult,
    QueryClient
} from '@tanstack/react-query';
import type { Router, AnyProcedure } from '@selix/core';
import type { InferProcedureInput, InferProcedureOutput, CreateClient } from '@selix/client';
import { createRecursiveProxy } from '@selix/client';

// We need to re-define or infer types since they might not be fully exported
// For simplicity in this iteration, we focus on the runtime proxy and basic type inference structure.

type ProcedureInput<T> = T extends AnyProcedure ? InferProcedureInput<T> : never;
type ProcedureOutput<T> = T extends AnyProcedure ? InferProcedureOutput<T> : never;

// Type for the vanilla client created by @selix/client
type VanillaClient<TRouter extends Router> = CreateClient<TRouter>;

const SelixContext = createContext<any>(null);

export function SelixProvider<TRouter extends Router>({
    client,
    children,
    queryClient
}: {
    client: CreateClient<TRouter>,
    children: React.ReactNode,
    queryClient?: QueryClient
}) {
    return (
        <SelixContext.Provider value={client}>
            {children}
        </SelixContext.Provider>
    );
}

export function useSelixContext<TRouter extends Router>() {
    const client = useContext(SelixContext);
    if (!client) {
        throw new Error('SelixProvider not found');
    }
    return client as VanillaClient<TRouter>;
}

// Type definitions for the proxy
export type DecoratedProcedure<TProcedure extends AnyProcedure> = {
    useQuery: <TData = ProcedureOutput<TProcedure>>(
        input: { input: ProcedureInput<TProcedure>, project?: any },
        opts?: Omit<UseQueryOptions<ProcedureOutput<TProcedure>, Error, TData>, 'queryKey' | 'queryFn'>
    ) => UseQueryResult<TData, Error>;

    useMutation: <TContext = unknown>(
        opts?: UseMutationOptions<ProcedureOutput<TProcedure>, Error, { input: ProcedureInput<TProcedure>, project?: any }, TContext>
    ) => UseMutationResult<ProcedureOutput<TProcedure>, Error, { input: ProcedureInput<TProcedure>, project?: any }, TContext>;
};

export type DecoratedRouter<TRouter extends Router> = {
    [K in keyof TRouter['_def']['procedures']]: TRouter['_def']['procedures'][K] extends Router
    ? DecoratedRouter<TRouter['_def']['procedures'][K]>
    : (TRouter['_def']['procedures'][K] extends AnyProcedure
        ? DecoratedProcedure<TRouter['_def']['procedures'][K]>
        : never);
};

export function createSelixReact<TRouter extends Router>(): DecoratedRouter<TRouter> {
    return createRecursiveProxy(({ path, prop, type }) => {
        if (type === 'get' && typeof prop === 'string') {
            if (prop === 'useQuery') {
                return (input: any, opts: any) => {
                    const client = useSelixContext<TRouter>();
                    const queryKey = [...path, input];

                    return __useQuery({
                        queryKey,
                        queryFn: () => {
                            let procedureObj: any = client;
                            for (const segment of path) {
                                procedureObj = procedureObj[segment];
                            }
                            return procedureObj.query(input);
                        },
                        ...opts
                    });
                };
            }

            if (prop === 'useMutation') {
                return (opts: any) => {
                    const client = useSelixContext<TRouter>();

                    return __useMutation({
                        mutationFn: (variables: any) => {
                            let procedureObj: any = client;
                            for (const segment of path) {
                                procedureObj = procedureObj[segment];
                            }
                            return procedureObj.mutation(variables);
                        },
                        ...opts
                    });
                }
            }
        }
        return undefined;
    }) as any;
}

// packages/solid-query/src/index.tsx
import { createContext, useContext, JSX } from 'solid-js';
import {
    createQuery as __createQuery,
    createMutation as __createMutation,
    SolidQueryOptions,
    SolidMutationOptions,
    UseQueryResult,
    UseMutationResult
} from '@tanstack/solid-query';
import type { Router, AnyProcedure } from '@selix/core';
import type { InferProcedureInput, InferProcedureOutput, CreateClient } from '@selix/client';

type ProcedureInput<T> = T extends AnyProcedure ? InferProcedureInput<T> : never;
type ProcedureOutput<T> = T extends AnyProcedure ? InferProcedureOutput<T> : never;
type VanillaClient<TRouter extends Router> = CreateClient<TRouter>;

const SelixContext = createContext<VanillaClient<any> | null>(null);

export function SelixProvider<TRouter extends Router>(props: {
    client: CreateClient<TRouter>,
    children: JSX.Element
}) {
    return (
        <SelixContext.Provider value={props.client}>
            {props.children}
        </SelixContext.Provider>
    );
}

export function useSelixContext<TRouter extends Router>() {
    const client = useContext(SelixContext);
    if (!client) {
        throw new Error('SelixProvider not found');
    }
    return client as VanillaClient<TRouter>;
}

export type DecoratedProcedure<TProcedure extends AnyProcedure> = {
    createQuery: <TData = ProcedureOutput<TProcedure>>(
        getOptions: () => { input: ProcedureInput<TProcedure>, project?: any } & Omit<SolidQueryOptions<ProcedureOutput<TProcedure>, Error, TData>, 'queryKey' | 'queryFn'>
    ) => UseQueryResult<TData, Error>;

    createMutation: <TContext = unknown>(
        options?: SolidMutationOptions<ProcedureOutput<TProcedure>, Error, { input: ProcedureInput<TProcedure>, project?: any }, TContext>
    ) => UseMutationResult<ProcedureOutput<TProcedure>, Error, { input: ProcedureInput<TProcedure>, project?: any }, TContext>;
};

export type DecoratedRouter<TRouter extends Router> = {
    [K in keyof TRouter['_def']['procedures']]: TRouter['_def']['procedures'][K] extends Router
    ? DecoratedRouter<TRouter['_def']['procedures'][K]>
    : (TRouter['_def']['procedures'][K] extends AnyProcedure
        ? DecoratedProcedure<TRouter['_def']['procedures'][K]>
        : never);
};

export function createSelixSolid<TRouter extends Router>(): DecoratedRouter<TRouter> {
    const createProxy = (path: string[]) => {
        return new Proxy(() => { }, {
            get(_target, prop) {
                if (typeof prop === 'string') {
                    if (prop === 'createQuery') {
                        return (getOptions: () => any) => {
                            const client = useSelixContext<TRouter>();

                            return __createQuery(() => {
                                const options = getOptions();
                                const { input, project, ...queryOpts } = options;

                                return {
                                    queryKey: [...path, input],
                                    queryFn: () => {
                                        let procedureObj: any = client;
                                        for (const segment of path) {
                                            procedureObj = procedureObj[segment];
                                        }
                                        return procedureObj.query({ input, project });
                                    },
                                    ...queryOpts
                                };
                            });
                        };
                    }

                    if (prop === 'createMutation') {
                        return (opts: any) => {
                            const client = useSelixContext<TRouter>();

                            return __createMutation(() => ({
                                mutationFn: (variables: any) => {
                                    let procedureObj: any = client;
                                    for (const segment of path) {
                                        procedureObj = procedureObj[segment];
                                    }
                                    return procedureObj.mutation(variables);
                                },
                                ...opts
                            }));
                        }
                    }

                    return createProxy([...path, prop]);
                }
                return createProxy(path);
            }
        });
    };

    return createProxy([]) as any;
}
