// examples/frontend-solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import { SelixProvider } from '@selix/solid-query';
import { vanillaClient } from './selix';
import App from './App';

const queryClient = new QueryClient();

render(
    () => (
        <QueryClientProvider client={queryClient}>
            <SelixProvider client={vanillaClient} queryClient={queryClient}>
                <App />
            </SelixProvider>
        </QueryClientProvider>
    ),
    document.getElementById('root') as HTMLElement
);

// examples/frontend-react/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { SelixProvider } from '@selix/react-query'
import { vanillaClient } from './utils/selix'

const queryClient = new QueryClient()

ReactDOM.createRoot(document.getElementById('root')!).render(
    <React.StrictMode>
        <QueryClientProvider client={queryClient}>
            <SelixProvider client={vanillaClient} queryClient={queryClient}>
                <App />
            </SelixProvider>
        </QueryClientProvider>
    </React.StrictMode>,
)
